### ISSUE TITLE
How to get C and D values (from chapter 6) from Windows ?

### ISSUE THREAD

**Issue by Vince1024** [marcelhoffs/input-switcher#11]
Hi,

Thank you very much for this awesome tool.

How to get C and D values (from chapter 6) without any access to Solaar on linux ?

I am able to switch MX Master 3 from channel 1 to 2 because I'm lucky to get the same values as you got.

But can't find my MX Key values.

All my systems are running Windows xx.

***
![image](https://user-images.githubusercontent.com/81962401/225903753-27c0532d-71b4-42cb-a08f-6c8d7dc48312.png)
***

**Comment by Vince1024** [comment]
Found by changing byte #2 to the good value.
Thanks

**Comment by meenmo** [comment]
Hi @Vince1024 

Could you kindly advise how did you get C & D values on Windows?

**Comment by ManuSquall** [comment]
Hello @Vince1024 , how did u manage to C and D please?

**Comment by meenmo** [comment]
I personally wrote a script to run all possible alphanumeric-combinations of C&D....

I think there should be a better way to do this.
