### ISSUE TITLE
Switch from Mac to Windows

### ISSUE THREAD

**Issue by pppaapp** [marcelhoffs/input-switcher#12]
I'm using MX MASTER 3S.

channel2 : mac(blutooth)
channel3 : windows(blutooth)

On Windows, I used this command with success.

```
hidapitester.exe --vidpid 046D:B034 --usage 0x0202 --usagePage 0xFF43 --open --length 11 --send-output 0x11,0x00,0x0A,0x1b,0x01,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00
```

But I don't know how to do it on a Mac.

**Comment by Skazzi00** [comment]
How did you solved this problem?

**Comment by pppaapp** [comment]
> How did you solved this problem?

The issue I was experiencing was due to Karabiner-Elements being enabled. 

After excluding Logitech keyboard from Karabiner-Elements, the problem was resolved
