### ISSUE TITLE
Can't switch back to channel 1

### ISSUE THREAD

**Issue by Gronlaender** [marcelhoffs/input-switcher#17]
I can switch to channel 2 without any problems, but is unable to switch back to channel 1.
Channel 1 is a windows 11 pc and channel 2 is a windows 10 pc.

I've modified the .bat file, but i'm not sure if its correct.

rem Switch MX Keys to channel 1
.\hidapitester.exe --vidpid 046D:C52B --usage 0x0001 --usagePage 0xFF00 --open --length 7 --send-output 0x10,0x01,0x09,0x1e,0x01,0x00,0x00

rem Switch MX Anywhere 3 to channel 1
.\hidapitester.exe --vidpid 046D:C52B --usage 0x0001 --usagePage 0xFF00 --open --length 7 --send-output 0x10,0x02,0x0a,0x1b,0x01,0x00,0x00

**Comment by Gronlaender** [comment]
I managed to solve the problem myself.

**Comment by Zayyad1453** [comment]
> I managed to solve the problem myself.

How did you do it, I think im facing a similar problem. Can switch but cannot switch back

**Comment by Gronlaender** [comment]
> > I managed to solve the problem myself.
> 
> How did you do it, I think im facing a similar problem. Can switch but cannot switch back

Probably a bad answer, but i read through the __modify the _script_ part. 

0x10,0x02,0x0a,0x1b,0x01,0x00,0x00 some of these numbers were wrong and found the mistake.

**Comment by Zayyad1453** [comment]
> > > I managed to solve the problem myself.
> > 
> > 
> > How did you do it, I think im facing a similar problem. Can switch but cannot switch back
> 
> Probably a bad answer, but i read through the **_modify the script_** part.
> 
> 0x10,0x02,0x0a,0x1b,0x01,0x00,0x00 some of these numbers were wrong and found the mistake.

Thanks for the quick response, I also found out how to make it work, I had modified the script on my computer with the logitech dongle, but the connection params and ids are quite different on the bluetooth connection.

For anyone with a similar issue:
### Switching from the logitech dongle connection on both my keyboard and mouse:

`
rem this bat file has usage and usage path config from a logitech BLUETOOTH UNIFYING RECEIVER CONNECTION on windows 10
rem --send-output flag has 7 variables for unifying receiver, see README reference below
rem		A always 0x01 
rem		B connection to unifying receiver 0x00 for channel 1, 0x01 for channel 2, 0x02 for channel 3 
rem		C ??? 
rem		D ???
rem		E connection to GO TO  
rem		F always 0x00 
rem		G always 0x00 
rem references:
rem 	README: https://github.com/marcelhoffs/input-switcher
rem 	BLUETOOTH CONNECTION ISSUE: https://github.com/marcelhoffs/input-switcher/issues/8#issuecomment-1383685583
rem 	Crude discovery method for B, C and D variables: 
rem 		https://github.com/marcelhoffs/input-switcher/issues/46
rem Switch MX Keys to channel 2
.\hidapitester.exe --vidpid 046D:C52B --usage 0x0001 --usagePage 0xFF00 --open --length 7 --send-output 0x10,0x02,0x08,0x1b,0x01,0x00,0x00
.\hidapitester.exe --vidpid 046D:C52B --usage 0x0001 --usagePage 0xFF00 --open --length 7 --send-output 0x10,0x02,0x08,0x1e,0x01,0x00,0x00

rem Switch MX Anywhere 3 to channel 2
.\hidapitester.exe --vidpid 046D:C52B --usage 0x0001 --usagePage 0xFF00 --open --length 7 --send-output 0x10,0x01,0x09,0x1b,0x01,0x00,0x00
.\hidapitester.exe --vidpid 046D:C52B --usage 0x0001 --usagePage 0xFF00 --open --length 7 --send-output 0x10,0x01,0x09,0x1e,0x01,0x00,0x00
`

### Switching from the bluetooth connection

`
rem this bat file has usage and usage path config from a BLUETOOTH DIRECT CONNECTION on windows 11
rem --send-output flag has 11 variables for unifying receiver, see README reference below
rem		A always 0x11 
rem		B connection always 0x00 for bluetooth direct connection
rem		C ??? 
rem		D ???
rem		E connection to GO TO  
rem		F always 0x00 
rem		G always 0x00 
rem		H always 0x00 
rem		I always 0x00 
rem		J always 0x00 
rem		K always 0x00 
rem references:
rem 	README: https://github.com/marcelhoffs/input-switcher
rem 	BLUETOOTH CONNECTION ISSUE: https://github.com/marcelhoffs/input-switcher/issues/8#issuecomment-1383685583
rem 	Crude discovery method for B, C and D variables: 
rem 		https://github.com/marcelhoffs/input-switcher/issues/46
rem Switch Keyboard to channel 1
.\hidapitester.exe --vidpid 046D:B33B --usage 0x0202 --usagePage 0xFF43 --open --length 11 --send-output 0x11,0x00,0x08,0x1b,0x00,0x00,0x00,0x00,0x00,0x00,0x00 
rem Switch Mouse to channel 2
.\hidapitester.exe --vidpid 046D:B015 --usage 0x0202 --usagePage 0xFF43 --open --length 11 --send-output 0x11,0x00,0x09,0x1E,0x00,0x00,0x00,0x00,0x00,0x00,0x00

`
