### ISSUE TITLE
Alternative to Solaar for windows 10

### ISSUE THREAD

**Issue by sbackp** [marcelhoffs/input-switcher#19]
Do you have an alternative to Solaar for generating the commands on windows?

My setup is two Windows 10 PC where I connect my Logitech devices (MX keys and MX Master 3) with unifying dongles. The input-switcher works out of the box with the keyboard but not with the mouse.

**Comment by d00m178** [comment]
any updates? how to use it only for 2 windows laptops?

**Comment by Id3aFly** [comment]
If you don't have a linux machine running, you could use virtual box.
