### ISSUE TITLE
i can't open the keyboard device on macOS Sonoma

### ISSUE THREAD

**Issue by pppaapp** [marcelhoffs/input-switcher#20]
This is the information on the keyboard

```
# hidapitester --list-detail

046D/B367: Logitech - MX MCHNCL M
  vendorId:      0x046D
  productId:     0xB367
  usagePage:     0x0001
  usage:         0x0006


046D/B367: Logitech - MX MCHNCL M
  vendorId:      0x046D
  productId:     0xB367
  usagePage:     0x000C
  usage:         0x0001


046D/B367: Logitech - MX MCHNCL M
  vendorId:      0x046D
  productId:     0xB367
  usagePage:     0xFF43
  usage:         0x0202
```

but the error appears that the device cannot be opened

```
# hidapitester --vidpid 046D:B367 --usage 0x0202 --usagePage 0xFF43 --timeout 2000 --open --read-input-forever --length 11 --read-feature 1

Opening device, vid/pid:0x046D/0xB367, usagePage/usage: FF43/202
Error: could not open device
Error on read: no device opened.
Error on read: no device opened.
```

it works fine on Windows

**Comment by jerem-uzoma** [comment]
Try with sudo:

`sudo hidapitester --vidpid 046D:B367 --usage 0x0202 --usagePage 0xFF43 --timeout 2000 --open --read-input-forever --length 11 --read-feature 1`

**Comment by pppaapp** [comment]
> Try with sudo:
> 
> `sudo hidapitester --vidpid 046D:B367 --usage 0x0202 --usagePage 0xFF43 --timeout 2000 --open --read-input-forever --length 11 --read-feature 1`

![CleanShot 2023-10-19 at 01 53 30](https://github.com/marcelhoffs/input-switcher/assets/31263588/06b60449-4941-4aeb-8a0c-2bf25ef8119a)

😢

The mouse works, but only the keyboard has problems

**Comment by Dentrax** [comment]
Running with `sudo` fixed my issue!
