### ISSUE TITLE
VBS (and .bat) not selectable as application with Logi Options

### ISSUE THREAD

**Issue by rloutrel** [marcelhoffs/input-switcher#23]
Is there a trick to select the vbs script?

**Comment by d00m178** [comment]
I have added BAT file in the Actions - Open Application
![image](https://github.com/marcelhoffs/input-switcher/assets/8877689/ae4c615b-8fee-4f44-9e67-0fabe427cfd0)

but sometime it seems to switch only mouse (master 3s) bat keyboard keep still connected to host1. so I need press this hotkey second time.
I use Bluetooth connection on the both laptops..

**Comment by Id3aFly** [comment]
Yes, vbs does not work for me either. Actually it is no problem and I don't mind seeing the short terminal popup. 
However, to make the popup be visible a bit shorter is to add "@echo off" as very first line. This will prevent the output of the REM commands and thus will only print the output of the Hidapi-Tool

**Comment by Ev0cati0** [comment]
Even though the browse file selector filters out .vbs, you can just copy the .vbs script full name in the 'File name:" text box and click open.

![Screenshot 2024-02-20 122843](https://github.com/marcelhoffs/input-switcher/assets/128390643/0449110f-0068-40bf-b911-09ec2e07c2e2)
