### ISSUE TITLE
Windows 11 not working.

### ISSUE THREAD

**Issue by holmbom** [marcelhoffs/input-switcher#5]
I have these on a Windows 10 and on my Mac. Works like a charm, but on my Windows 11 i seem not to get it working?
Have anyone else seen some issues with Windows 11?

It says -1 bytes written.
.\hidapitester.exe --vidpid 046D:C52B --usage 0x0001 --usagePage 0xFF00 --open --length 7 --send-output 0x10,0x01,0x09,0x1e,0x01,0x00,0x00
.\hidapitester.exe --vidpid 046D:C52B --usage 0x0001 --usagePage 0xFF00 --open --length 7 --send-output 0x10,0x02,0x0a,0x1b,0x01,0x00,0x00

// Erik

**Comment by holmbom** [comment]
I solved it, program working lika a charm! :)

**Comment by Dak0r** [comment]
Hi, would your mind sharing what your issue was and how you solved it?
Maybe others run into the same problem 🙂

**Comment by MSchmack** [comment]
It seems to work just fine on windows 11. I suspect the issue creator used the logitech bolt reciever unlike the github creator which used the original logitech reciever. Their default hardware id seems to differ (tested on two devices).

Default hardware id on windows 11 for logitech bolt devices seems to be 046D:C548 or as part of the command:
--vidpid 046D:C548 

The process of finding the hardware id of your reciever is explained in the chapter "6 - Modify the scripts"

FYI @keysmaster86
